version: '3'

services:
  app:
    build:.
    ports:
      - "5000:5000"
    volumes:
      -./app:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
